In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.datasets import make_regression
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.linear_model import LinearRegression
from sklearn.datasets import make_hastie_10_2
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import AdaBoostRegressor
from sklearn.datasets import make_classification

In [2]:
bl=pd.read_csv("C:/Users/Mano/Documents/hello/train.csv")

In [3]:
bl.isnull().mean()

User_ID                       0.000000
Product_ID                    0.000000
Gender                        0.000000
Age                           0.000000
Occupation                    0.000000
City_Category                 0.000000
Stay_In_Current_City_Years    0.000000
Marital_Status                0.000000
Product_Category_1            0.000000
Product_Category_2            0.315666
Product_Category_3            0.696727
Purchase                      0.000000
dtype: float64

In [4]:
bl.drop(["Product_Category_3","Product_ID","User_ID"],axis=1,inplace=True)

In [5]:
bl.Product_Category_2.fillna(bl.Product_Category_2.mean(),inplace=True)

In [6]:
bl.isnull().mean()

Gender                        0.0
Age                           0.0
Occupation                    0.0
City_Category                 0.0
Stay_In_Current_City_Years    0.0
Marital_Status                0.0
Product_Category_1            0.0
Product_Category_2            0.0
Purchase                      0.0
dtype: float64

In [7]:
dummie=pd.get_dummies(bl)

In [8]:
dummie.shape

(550068, 22)

In [9]:
dummie.head()

Occupation  Marital_Status  Product_Category_1  Product_Category_2  \
0          10               0                   3            9.842329   
1          10               0                   1            6.000000   
2          10               0                  12            9.842329   
3          10               0                  12           14.000000   
4          16               0                   8            9.842329   

   Purchase  Gender_F  Gender_M  Age_0-17  Age_18-25  Age_26-35  ...  \
0      8370         1         0         1          0          0  ...   
1     15200         1         0         1          0          0  ...   
2      1422         1         0         1          0          0  ...   
3      1057         1         0         1          0          0  ...   
4      7969         0         1         0          0          0  ...   

   Age_51-55  Age_55+  City_Category_A  City_Category_B  City_Category_C  \
0          0        0                1                0                0   
1          0        0                1                0                0   
2          0        0                1                0                0   
3          0        0                1                0                0   
4          0        1                0                0                1   

   Stay_In_Current_City_Years_0  Stay_In_Current_City_Years_1  \
0                             0                             0   
1                             0                             0   
2                             0                             0   
3                             0                             0   
4                             0                             0   

   Stay_In_Current_City_Years_2  Stay_In_Current_City_Years_3  \
0                             1                             0   
1                             1                             0   
2                             1                             0   
3                             1                             0   
4                             0                             0   

   Stay_In_Current_City_Years_4+  
0                              0  
1                              0  
2                              0  
3                              0  
4                              1  

[5 rows x 22 columns]

In [10]:
x=dummie.drop(["Purchase"],axis=1)

In [11]:
y=dummie["Purchase"]

In [12]:
trainx,testx,trainy,testy=train_test_split(x,y,test_size=0.2,random_state=42)

# LinearRegression

In [13]:
model=LinearRegression().fit(trainx,trainy)

In [14]:
model.predict(testx)

array([12675.48154039, 10322.29010269,  7171.04344628, ...,
        8172.27963925,  6664.08576885,  9428.61798717])

In [63]:
m=model.score(testx,testy)

In [64]:
m

0.127332826592915

In [16]:
rme=sqrt(mean_squared_error(testy,model.predict(testx),squared=False))

In [17]:
rme

68.4295645447702

# DecisionTreeRegressor

In [18]:
dt=DecisionTreeRegressor(random_state=0)
dt.fit(trainx,trainy)

DecisionTreeRegressor(random_state=0)

In [19]:
dt.predict(testx)

array([13889.5       , 11899.        ,  7449.25      , ...,
        6966.64285714,  4423.        ,  9653.08571429])

In [65]:
s=dt.score(testx,testy)

In [66]:
s

0.6010772577057202

In [21]:
rme2=sqrt(mean_squared_error(testy,dt.predict(testx),squared=False))

In [22]:
rme2

56.267007124242454

# RandomForestRegressor

In [23]:
rf=RandomForestRegressor(random_state=0)
rf.fit(trainx,trainy)

RandomForestRegressor(random_state=0)

In [24]:
rf.predict(testx)

array([13787.05036508, 12875.66473208,  8405.14715512, ...,
        6884.87221995,  3985.95222222,  9695.64792192])

In [67]:
d=rf.score(testx,testy)

In [68]:
d

0.6354945597565536

In [26]:
rme3=sqrt(mean_squared_error(testy,rf.predict(testx),squared=False))

In [27]:
rme3

55.01202352850247

# GradientBoostingRegressor

In [28]:
clf = GradientBoostingRegressor(n_estimators=100, learning_rate=1.0,max_depth=1, random_state=0).fit(trainx, trainy)

In [29]:
s=clf.predict(testx)

array([13893.60524699, 13301.8987448 ,  7375.24813262, ...,
        7283.60755233,  4723.37183602,  8678.91968873])

In [69]:
g=clf.score(testx,testy)

In [70]:
g

0.618786701126588

In [31]:
rme4=sqrt(mean_squared_error(testy,clf.predict(testx),squared=False))

In [32]:
rme4

55.631865985682545

#  AdaBoostRegressor

In [33]:
clf2 = AdaBoostRegressor(n_estimators=100, random_state=0).fit(trainx,trainy)

In [34]:
clf2.predict(testx)

array([13156.42571572, 12600.97930678, 10461.44194134, ...,
       10461.44194134,  7612.76440186, 10104.21693514])

In [71]:
c=clf2.score(testx,testy)

In [72]:
c

0.40295580591337843

In [36]:
rme5=sqrt(mean_squared_error(testy,clf2.predict(testx),squared=False))

In [37]:
rme5

62.23479112455758

In [51]:
pip install prettytable 

In [75]:
from tabulate import tabulate

In [77]:
mydata = [
    ["LinearRegression",m],
    ["decision_tree_regressor", s],
    ["random_forest_regression", d],
    ["gradient_boosting_regression",g],
    ["ada_boosting_regression",c]
    ]

In [88]:
head1 = ["Method", "score"]

In [89]:
print(tabulate(mydata, headers=head1, tablefmt="grid"))

+------------------------------+----------+
| Method                       |    score |
+==============================+==========+
| LinearRegression             | 0.127333 |
+------------------------------+----------+
| decision_tree_regressor      | 0.601077 |
+------------------------------+----------+
| random_forest_regression     | 0.635495 |
+------------------------------+----------+
| gradient_boosting_regression | 0.618787 |
+------------------------------+----------+
| ada_boosting_regression      | 0.402956 |
+------------------------------+----------+


In [79]:
mydata2 = [
    ["LinearRegression",rme],
    ["decision_tree_regressor",rme2],
    ["random_forest_regression", rme3],
    ["gradient_boosting_regression",rme4],
    ["ada_boosting_regression",rme5]
    ]

In [82]:
head = ["Method", "rootmean"]

In [84]:
print(tabulate(mydata2, headers=head, tablefmt="grid"))

+------------------------------+------------+
| Method                       |   rootmean |
+==============================+============+
| LinearRegression             |    68.4296 |
+------------------------------+------------+
| decision_tree_regressor      |    56.267  |
+------------------------------+------------+
| random_forest_regression     |    55.012  |
+------------------------------+------------+
| gradient_boosting_regression |    55.6319 |
+------------------------------+------------+
| ada_boosting_regression      |    62.2348 |
+------------------------------+------------+
